import { MigrationInterface, QueryRunner } from 'typeorm';

export class RebuildClubsForCategoryAndCreator1761000000003
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "clubs" CASCADE`);

    await queryRunner.query(`
      CREATE TABLE "clubs" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "name" varchar(100) NOT NULL,
        "categoryId" uuid NOT NULL,
        "creatorId" uuid NOT NULL,
        "description" text,
        "isActive" boolean NOT NULL DEFAULT true,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_clubs_name_unique" ON "clubs" ("name")`,
    );
    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'FK_clubs_categoryId'
        ) THEN
          ALTER TABLE "clubs"
          ADD CONSTRAINT "FK_clubs_categoryId"
          FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE RESTRICT;
        END IF;
      END
      $$;
    `);
    // creatorId FK intentionally omitted (users table may not exist in all environments)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "clubs" CASCADE`);

    await queryRunner.query(`
      CREATE TABLE "clubs" (
        "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "name" varchar(100) NOT NULL,
        "description" text,
        "isPublic" boolean NOT NULL DEFAULT true,
        "ownerId" int,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_clubs_name_unique" ON "clubs" ("name")`,
    );
  }
}
