import { MigrationInterface, QueryRunner } from 'typeorm';

export class RebuildCategoriesForSlug1761000000002
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "categories" CASCADE`);

    await queryRunner.query(`
      CREATE TABLE "categories" (
        "id" uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
        "name" varchar(100) NOT NULL,
        "slug" varchar(100) NOT NULL,
        "description" text,
        "icon" varchar(255),
        "isActive" boolean NOT NULL DEFAULT true,
        "createdAt" timestamptz NOT NULL DEFAULT now(),
        "updatedAt" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_categories_name_unique" ON "categories" ("name")`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_categories_slug_unique" ON "categories" ("slug")`,
    );

    await queryRunner.query(`
      INSERT INTO "categories" ("name", "slug")
      VALUES
        ('datascience', 'datascience'),
        ('ai', 'ai'),
        ('cybersecurity', 'cybersecurity'),
        ('frontend', 'frontend'),
        ('backend', 'backend'),
        ('uiux', 'uiux')
      ON CONFLICT DO NOTHING
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE IF EXISTS "categories" CASCADE`);

    await queryRunner.query(`
      CREATE TABLE "categories" (
        "id" int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "name" varchar(100) NOT NULL,
        "description" text,
        "image" varchar(1024)
      )
    `);

    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_categories_name_unique" ON "categories" ("name")`,
    );
  }
}
